core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    stripe_config,
    create_checkout_session,
    MyOrders,
    thank,
    get_phonepe_creds
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('config/', stripe_config),  # new
    path('create-checkout-session/', create_checkout_session), # new
    path('my-orders/', MyOrders.as_view(), name='my-orders'), # new
    path('order-confirm/', thank,  name='order-confirm'), # new

    path('phonepe/', get_phonepe_creds,  name='phonepe'), # new


    
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField

# Create your models here.
CATEGORY_CHOICES = (
    ('SB', 'Shirts And Blouses'),
    ('TS', 'T-Shirts'),
    ('SK', 'Skirts'),
    ('HS', 'Hoodies&Sweatshirts')
)

LABEL_CHOICES = (
    ('S', 'sale'),
    ('N', 'new'),
    ('P', 'promotion')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Slide(models.Model):
    caption1 = models.CharField(max_length=100)
    caption2 = models.CharField(max_length=100)
    link = models.CharField(max_length=100)
    image = models.ImageField(help_text="Size: 1920x570")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "{} - {}".format(self.caption1, self.caption2)

class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:category", kwargs={
            'slug': self.slug
        })


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    stock_no = models.CharField(max_length=10)
    description_short = models.CharField(max_length=50)
    description_long = models.TextField()
    image = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'BillingAddress', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'BillingAddress', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a BillingAddress
    (Failed Checkout)
    3. Payment
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return str(self.id)

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    # def __str__(self):
    #     return "{}'s address is {} {} {}".format(self.user, self.street_address, self.apartment_address, self.zip )

    class Meta:
        verbose_name_plural = 'BillingAddresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + " paid " + str(self.amount)


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


# {% if order.being_delivered %}
# <li class="step0 active text-center" id="step3"></li>
# {% else %}
# <li class="step0 text-center" id="step3"></li>
# {% endif %}
# {% if order.received %}
# <li class="step0 active text-center" id="step4"></li>
# {% else %}
# <li class="step0 text-center" id="step4"></li>
# {% endif %}

templates/nav.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}

<style>
	.topbar {
		background-color: white;
		color: black !important;
	}
	.topbar a:hover{
		color: black;
	}
	.sub-menu {
        display: none; /* Hide the submenu by default */
        transition: max-height 10s ease; /* Add transition for smooth animation */
        overflow: hidden; /* Hide any content that overflows the submenu */
        max-height: 0; /* Set max-height to 0 to make it hidden */
    }

    .sub-menu.show {
        display: block; /* Show the submenu when it has the 'show' class */
        max-height: 200px; /* Set max-height to a value large enough to display the submenu content */
    }
</style>
<!-- Header -->
<header class="header1">
		<!-- Header desktop -->
		<div class="container-menu-header">
			<div class="wrap_header">
				<!-- Logo -->
				<a href="/" class="logo">
					<p style="color: black; "><b style="font-size: 22px;">M</b>Y SHOP</p>
				</a>

				<!-- Menu -->
				<div class="wrap_menu sticky-top">
					<nav class="menu">
						<ul class="main_menu">
							<li>
								<a href="/">Home</a>

							</li>

							<li>
								<a href="/shop/">Shop</a>
							</li>

							{% categories %}
							

							{% if request.user.is_authenticated %}
							<li>
								<a href="{% url 'core:my-orders' %}">My orders</a>
							</li>
							<li>
								<div class="header-wrapicon2">
								<a href="{% url 'core:order-summary' %}">
									
									<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">{{ request.user|cart_item_count }}</span>
									</a>
								</div>
							</li>

							
							<li>
								<a href="{% url 'account_logout' %}">Logosut</a>
							</li>
							
							{% else %}
							<li>
								<a href="{% url 'account_login' %}">Login</a>
								<ul class="sub_menu sub-menu">
									<li><a href="{% url 'account_login' %}">Login</a></li>
									<li><a href="{% url 'account_signup' %}">SignUp</a></li>
								</ul>
							</li>
							{% endif %}
							
						</ul>
					</nav>
				</div>

				
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap_header_mobile">
			<!-- Logo moblie -->
			<a href="/" class="logo-mobile">
				My Shop
				{% comment %} <img src="{% static 'images/icons/logo.png' %}" alt="IMG-LOGO"> {% endcomment %}
			</a>

			<!-- Button show menu -->
			<div class="btn-show-menu">
				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">
					{% comment %} <a href="#" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a> {% endcomment %}

					<span class="linedivide2"></span>
					
				</div>

				<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">
					<li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile" style="display:none;">
							<a href="#" class="topbar-social-item fa fa-facebook"></a>
							<a href="#" class="topbar-social-item fa fa-instagram"></a>
							<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
							<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
							<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
						</div>
					</li>

					<li class="item-menu-mobile">
						<a href="/">Home</a>
					</li>

					<li class="item-menu-mobile">
						<a href="/shop">Shop</a>
					</li>

					{% categories_mobile %}

					{% if request.user.is_authenticated %}
					<li class="item-menu-mobile">
						<a href="{% url 'core:order-summary' %}">Cart<span class="badge badge-dark" style="margin-left:5px">{{ request.user|cart_item_count }}</span></a>
					</li>
					<li class="item-menu-mobile">
						<a href="{% url 'account_logout' %}">Logout</a>
					</li>
					{% else %}
					<li class="item-menu-mobile">
						<a href="{% url 'account_login' %}" id="loginLink">Login</a>
						<ul class="sub-menu">
							<li><a href="{% url 'account_login' %}">Login</a></li>
							<li><a href="{% url 'account_signup' %}">SignUp</a></li>
						</ul>
						{% comment %} <i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i> {% endcomment %}
					</li>
					{% endif %}

				</ul>
			</nav>
		</div>
	</header>

	<script>
		document.getElementById("loginLink").addEventListener("click", function(event) {
			event.preventDefault(); // Prevent default link behavior
			var subMenu = this.nextElementSibling; // Get the next sibling, which is the <ul> element
			subMenu.classList.toggle("show"); // Toggle the "show" class to display/hide the submenu
		});
	</script>

templates/order_snippet.html
   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}


    </style>
  
 
    

   

    <div class="col-md-4 order-md-2 mb-4" style="background: #fff;">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted">quantity : {{ order_item.quantity }}</small>
          </div>
          <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{order.coupon.code}}</small>
          </div>
          <span class="text-success">-${{ order.coupon.amount }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong>${{ order.get_total }}</strong>
        </li>
      </ul>
      
      {% if DISPLAY_COUPON_FORM %}
      <form method="POST" action="{% url 'core:add-coupon' %}" class="card p-2">
        {% csrf_token %}
        <div class="input-group">
          {{ couponform.code }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>

  

templates/order_summary.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<style>
    .container {
      font-family: "-apple-system", sans-serif;

  }
  
  .container * {
      font-size: 16px;
  }
  .parent-div{
    background: #f0f0f08a;
    margin-top:50px;
  }

  .btn-primary{
    background-color:#b2b6b5;
	border:1px #b2b6b5;
	color: black;
  }
    </style>
<div class="parent-div">
<div class="container">
  <div class="row" style="margin-left:auto; margin-right:auto;">
    <div class="col-lg-12">
      <h2>Order Summary</h2>

      <section class="h-100 h-custom">
        <div class="container h-100 py-5">
            <div class="row d-flex justify-content-center align-items-center h-100" style="margin-left:auto; margin-right:auto;">
                <div class="col">
                    {{ cart_items }}
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Product Image</th>
                                    <th scope="col">Product Name</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Qty</th>
                                    <th scope="col">Total Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order_item in object.items.all %}
                                <tr>
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td>
                                        <img src="{{ order_item.item.image.url }}" class="img-fluid rounded-3" style="width: 120px;" alt="{{ order_item.item.title }}">
                                    </td>
                                    <td>
                                        <p class="mb-2">{{ order_item.item.title }}</p>
                                        <p class="mb-0">{{ order_item.item.author }}</p>
                                    </td>
                                    <td>₹{{ order_item.item.price }}</td>
                                    <td>
                                        <div class="d-flex flex-row">
                                          <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}">

                                            <button data-mdb-button-init data-mdb-ripple-init class="btn btn-link px-2" onclick="updateQuantity('{{ order_item.id }}', -1)">
                                                <i class="fas fa-minus"></i>
                                            </button>
                                          </a>
    
                                            <input id="quantity_{{ order_item.id }}" min="0" name="quantity" value="{{ order_item.quantity }}" type="number" class="form-control form-control-sm" style="width: 50px;" />

                                            <a href="{% url 'core:add-to-cart' order_item.item.slug %}">
                                            
                                            <button data-mdb-button-init data-mdb-ripple-init class="btn btn-link px-2" onclick="updateQuantity('{{ order_item.id }}', 1)">
                                                <i class="fas fa-plus"></i>
                                            </button>
                                          </a>
                                        </div>
                                    </td>
                                    <td>₹{{ order_item.get_total_item_price }}</td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="6">Your cart is empty</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
    
                    <div class="shadow-2-strong mb-5 mb-lg-0" style="border-radius: 16px;">
                        <div class="card-body p-4">
                            <div class="d-flex justify-content-between" style="font-weight: 500;">
                                <p class="mb-2">Subtotal</p>
                                <p class="mb-2">₹{{ object.get_total }}</p>
                            </div>
    
                            <div class="d-flex justify-content-between" style="font-weight: 500;">
                                <p class="mb-0">Shipping</p>
                                <p class="mb-0">₹20</p> <!-- Assuming static shipping cost -->
                            </div>
    
                            <hr class="my-4">
    
                            <div class="d-flex justify-content-between mb-4" style="font-weight: 500;">
                                <p class="mb-2">Total (tax included)</p>
                                <p class="mb-2">₹10</p>
                            </div>
    
                            <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block btn-lg" onclick="window.location.href='/checkout'">
                                <div class="d-flex justify-content-between">
                                    <span>Checkout</span>
                                    <span>₹{{ object.get_total|add:10|add:20 }}</span>
                                </div>
                            </button>
    
                        </div>
                    </div>
    
                </div>
            </div>
        </div>
    </section>

    <script>
      // Function to update quantity
      {% comment %} function updateQuantity(itemId, change) {
          const quantityInput = document.getElementById('quantity_' + itemId);
          let newQuantity = parseInt(quantityInput.value) + change;
          if (newQuantity < 0) {
              newQuantity = 0; // Ensure quantity doesn't go below 0
          }
          quantityInput.value = newQuantity;
          // You may need to implement AJAX to update the quantity in the server-side cart data
      } {% endcomment %}
  </script>






      {% comment %} <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product Image</th>
            <th scope="col">Product Name</th>

            <th scope="col">Price</th>
            <th scope="col">Qty</th>
            <th scope="col">Total Price</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
			<img src="{{ order_item.item.image.url }}" style="width: 130px;"> 
            </td>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
            	<a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-3"></i></a>
            	{{ order_item.quantity }}
            	<a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-3"></i></a>
            </td>
            <td>
              {% if order_item.item.discount_price %}
                  ₹{{ order_item.get_total_discount_item_price}}
                  <span class="badge badge-primary">  Saving ₹{{ order_item.get_amount_saved }}</span>
              {% else %}
                  ₹{{ order_item.get_total_item_price}}
              {% endif %}
              <a style="color: red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
              	<i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
			<td colspan="5">Your cart is empty</td>
          </tr>
        </tbody>
        {% endfor %}
        {% if object.coupon %}
        <tr>
          <td colspan="5"><b>Coupon : </b></td>
          <td>- ₹{{ object.coupon.amount }}</td>
        </tr>
        {% endif%}
        {% if object.get_total %}
        <tr>
        	<td colspan="5"><b>Order Total : </b></td>
        	<td><b>₹{{ object.get_total }}</b></td>
        </tr>
        <tr>
        	<td colspan="5">
        		<a href="/checkout" class="btn btn-warning float-right ml-2">Checkout</a>
        		<a href="/" class="btn btn-primary float-right">Continue Shopping</a>

        	</td>
        </tr>
        {% endif %}
      </table> {% endcomment %}
    </div>
  </div>
</div>
</div>
{% endblock content %}

templates/request_refund.html
{% extends 'base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block content %}


<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-3 mt-3">
      <h2>Request Refund</h2>
      <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
     
    </div>
  </div>
</div>

{% endblock content %}